### ISSUE TITLE
"raise ValueError('First step cannot be zero.')" in the training stage

### ISSUE THREAD

**Issue by yh570** [Bellspringsteen/OurCamera#10]
In the training stage with command:
python models-master/research/object_detection/train.py     --logtostderr    
    --pipeline_config_path=./data/faster_rcnn_resnet101_cars.config  
    --train_dir=./data/models/model/train
shows the error message: "raise ValueError('First step cannot be zero.')".

eval.py and tensorboard --logdir=./data/models/model/ works well. 

I confirmed all the paths in generate_tfrecord.py and faster_rcnn_resnet101_cars.config are correct, and test.record and train.record was generated successfully(I don't know the content are correct, if there is a method to check them please let me know). Would you please let me know the possible situation may cause the problem? Thank you.

**Comment by danp** [comment]
It looks like object detection was recently changed to add this error in https://github.com/tensorflow/models/pull/3656. Maybe try using the commit before that was merged, such as with:

```sh
git clone https://github.com/tensorflow/models
cd models
git checkout -b before-object-detection-changes 2913cb24ecb16ba955006b41072adce45c5a0f62
```

**Comment by Bellspringsteen** [comment]
Hello,

Great you created the .records. You make the train and eval empty folders yourself. Then when you call train.py it will fill those folders with checkpoints and frozen points for models that you can use later.

**Comment by danp** [comment]
Looking at https://github.com/tensorflow/models/issues/3794, maybe this is no longer valid?

https://github.com/Bellspringsteen/OurCamera/blob/796dbfbf2d73c2520db3da40838985f042da49dd/data/faster_rcnn_resnet101_cars.config#L92
