### ISSUE TITLE
Colons in /data/labels XML files prevents them from being checked out on Windows and Mac

### ISSUE THREAD

**Issue by streamtree** [Bellspringsteen/OurCamera#3]
The Windows and Mac file systems don't allow colons in filenames, which means that checking out the project generates multiple errors like the following:

`error: unable to create file data/labels/2017-12-27 12:14:19.731720.xml: Invalid argument`

**Comment by cclauss** [comment]
Ever since OSX, Macs are based on Darwin (Unix) and no longer have problems with colons in filenames.  I was able to clone this repo on both my Mac and iPad (using Working Copy) without issues.

**Comment by Bellspringsteen** [comment]
Just seeing this now. I was not aware that Windows computers couldn't handle colons. I can take a look at renaming all the files.
