### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by aaronbauman** [Bellspringsteen/OurCamera#8]
What does this mean, from the README?

> Look at your tensorflow eval images to gauge when to stop.

Where do i find tensorflow eval images?

**Comment by Bellspringsteen** [comment]
Hello,

While you are running train.py you should also run the tensorboard command. It will print out something like 

TensorBoard 0.4.0rc3 at http://Alexs-MacBook-Air-5.local:6006 (Press CTRL+C to quit)

If you then go to that url in your browser you will tensorboards graphs of your total loss, etc. You can also see test images and the annotations of the vehicles. Those eval images are a good indicator of when to stop training.
